### ISSUE TITLE
#[derive(Debug)] for Request

### ISSUE THREAD

**Issue by phil-n** [alexcrichton/curl-rust#101]
I just played with a REST API and had to fire up Wireshark in order to see what the request looked like in detail (including headers). It would be far easier to see whats going on if Debug was implemented for Request.

Otherwise, great crate!
Phil

**Comment by alexcrichton** [comment]
I've got an API rewrite in progress over at https://github.com/alexcrichton/curl-rust/pull/105, and unfortunately this may be difficult to do so now as I don't think that libcurl exposes this kind of information. If it does though it should be pretty easy to add!

**Comment by alexcrichton** [comment]
Closing as this API has long since been removed (and `Debug` is implemented everywhere now)
