### ISSUE TITLE
curl_formadd() is unavailable

### ISSUE THREAD

**Issue by sector-f** [alexcrichton/curl-rust#112]
I'm currently trying to write a file upload program. This requires sending data to a form (analogous to `curl -F` from the command line). I've been told that the equivalent function in native libcurl is `curl_formadd()`, but this function [is commented out](https://github.com/alexcrichton/curl-rust/blob/master/curl-sys/lib.rs#L907-L909) in the curl_sys crate. And, of course, this means there's no corresponding function in the curl crate.

**Comment by alexcrichton** [comment]
Ah yes, right! I had some difficulty initially with some CI and decided to not bind them in the first pass, I'll take a look now at binding them and see how it goes.

**Comment by alexcrichton** [comment]
Ok, lemme know if that works for you!

**Comment by sector-f** [comment]
Well, it *looks* good...but I honestly don't know enough about curl (yet) to tell if it works.

What's the correct way to take a PathBuf and then upload the corresponding file to a form?

**Comment by alexcrichton** [comment]
I believe that would [look like this](https://github.com/alexcrichton/curl-rust/blob/master/tests/post.rs#L80-L108)

**Comment by sector-f** [comment]
Seems like a step in the right direction, but I can't get it to work—though I'm willing to bet it's my fault. Here's my function:
````
fn upload_files(url: String, files: Vec<PathBuf>, _concurrent_uploads: u32) {
    curl::init();
    let mut handle = Easy::new();
    for file in &files {
        let mut form = Form::new();
        form.part("file").file(&file).add().unwrap();

        handle.url(&url).unwrap();
        handle.httppost(form).unwrap();

        handle.write_function(|a| {
            Ok(stdout().write(a).unwrap())
        }).unwrap();

        handle.perform().unwrap();
    }
}
````

However, `handle.perform()` is returning an Err, `[26] Failed to open/read local data from file/application`

**Comment by alexcrichton** [comment]
Hm and you're sure all those files exist? You may be able to use `strace` as well to figure out which syscall curl is issuing that's failing

**Comment by sector-f** [comment]
Hm, it apparently works with an absolute path but not with a relative one.

**Comment by alexcrichton** [comment]
Hm that's odd, the test I have is using a relative path...

**Comment by sector-f** [comment]
Actually, correction:  `./foo.jpg` works but `foo.jpg` does not.

**Comment by alexcrichton** [comment]
Oh weird, do you have an example that doesn't work in terms of a concrete setup?

**Comment by sector-f** [comment]
Oh, dear. It just got weirder.

`./target/debug/curl_main room.jpg` (what I'd been trying) fails. So I just copied another picture to the directory.

`./target/debug/curl_main ocean.jpg` succeeds.
