### ISSUE TITLE
DELETE and PATCH Functionality

### ISSUE THREAD

**Issue by mgattozzi** [alexcrichton/curl-rust#115]
I've been working on creating Github API Bindings using this library and it's been working out great, the only problem being that a DELETE or PATCH request is not implemented. Even if libcurl doesn't provide it using the easy interface it could be implemented with [this C function](https://curl.haxx.se/libcurl/c/CURLOPT_CUSTOMREQUEST.html). Are there plans to implement this sometime in the future? If they are is there some way I could help to implement it and how would I go about doing so?

**Comment by alexcrichton** [comment]
I think this should be bound through the [`custom_request` method](http://alexcrichton.com/curl-rust/curl/easy/struct.Easy.html#method.custom_request), does that work here?

**Comment by mgattozzi** [comment]
Ah can't believe I missed that in the docs. It's the binding to what I linked. I'll test it out when I get the chance and close this out if it's what I need, which I believe will be the case!

**Comment by mgattozzi** [comment]
That was what I needed! Thanks for the guidance!
