### ISSUE TITLE
Build fail on Windows with gcc ver. 0.3.30

### ISSUE THREAD

**Issue by LeMoussel** [alexcrichton/curl-rust#116]
[crate gcc](https://crates.io/crates/gcc) are updated to 0.3.30 on Jul 13, 2016.
When I compil on Windows 10, I got this error :

> Compiling curl-sys v0.2.0
> error: failed to run custom build command for `curl-sys v0.2.0`
> Process didn't exit successfully: `C:\Users\RUST Project\htmlparser\target\release\build\curl-sys-81c7fcebd44133fa\build-script-build` (exit code: 101)
> 
> "cargo build --release" completed with code 101

I update to gcc Ver. 0.3.28 in cargo.toml like this :
```
[dependencies]
curl = "*"
gcc = "= 0.3.28"
```
It's work fine.

**Comment by alexcrichton** [comment]
Thanks! Could you also gist the full error logs of what happened as well? It's failing locally for me as well and I'm investigating, but just want to make sure we're hitting the same error.

**Comment by LeMoussel** [comment]
I'm newbie in Rust. How can I get full error logs?

**Comment by alexcrichton** [comment]
Oh they *should* be printed to the console, but if they're not there then there's more hunting to do!

**Comment by alexcrichton** [comment]
Ok, pushed a new build of gcc-rs to 0.3.31 which I think should fix this. If you still have problems though let me know!

**Comment by LeMoussel** [comment]
Same problem

>  Downloading libz-sys v1.0.5
>  Downloading gcc v0.3.31
>    Compiling gcc v0.3.31
>    Compiling curl-sys v0.2.0
>    Compiling libz-sys v1.0.5
> error: failed to run custom build command for `curl-sys v0.2.0`
> Process didn't exit successfully: `C:\Users\lemoussel\OneDrive\RUST Project\htmlparser\target\release\build\curl-sys-81c7fcebd44133fa\build-script-build` (exit code: 101)
> 
> "cargo build --release" completed with code 101

**Comment by alexcrichton** [comment]
Hm it's surprising that nothing else is printed, what are the contents of: `target/release/build/curl-sys-81c7fcebd44133fa/output`?

Also, what version of Cargo are you using?

**Comment by LeMoussel** [comment]
> C:\Users\lemoussel\OneDrive\RUST Project\htmlparser>cargo --version
> cargo 0.11.0-nightly (259324c 2016-05-20)
> 
> C:\Users\lemoussel\OneDrive\RUST Project\htmlparser>rustc --version
> rustc 1.10.0 (cfcb716cf 2016-07-03)

I'm use Rust 1.10.0 Windows 64 bit (MSVC ABI)

Contents of: target/release/build/curl-sys-81c7fcebd44133fa/[output.zip](https://github.com/alexcrichton/curl-rust/files/365269/output.zip)

**Comment by alexcrichton** [comment]
Hm I wonder if that output file is stale, it's showing success but Cargo thinks the build script is failing! Could you try removing it, re-running, and see if it's recreated?

**Comment by alexcrichton** [comment]
So another thing I'm worried about is that https://github.com/rust-lang/cargo/pull/2630 changed how Cargo reads stdout/stderr of build scripts, and something about that may be wrong which hides the stdout/stderr of build scripts by accident. It seems that all the diagnostics printed out by the build script are getting shoved under the rug somewhere...
