### ISSUE TITLE
http digest authorization

### ISSUE THREAD

**Issue by silvio** [alexcrichton/curl-rust#120]
Is it possible with `curl-rust` to handle http digest authorization?

**Comment by alexcrichton** [comment]
Currently this isn't supported, but if libcurl itself does I'd be more than willing to add a binding! Otherwise though custom headers are allowed so that's likely be the route to take.

**Comment by silvio** [comment]
hmm, okay  
I think its supported. I see via `curl --libcurl x.txt ...` following lines in the output file

```c
curl_easy_setopt(hnd, CURLOPT_USERPWD, "user:pass");
curl_easy_setopt(hnd, CURLOPT_HTTPAUTH, (long)CURLAUTH_DIGEST);
```
All `CURLAUTH*` and `CURLOPT*` are reflected in `curl_sys` too.

**Comment by silvio** [comment]
Yeeeaah! Thanks @alexcrichton
