### ISSUE TITLE
cargo build needs to be run twice to succeed

### ISSUE THREAD

**Issue by dovreshef** [alexcrichton/curl-rust#121]
Hi,

Trying to build one of the examples on a newly created cargo project, cause the build to fail with the (final) error of 

```
--- stderr
fatal: Not a git repository (or any of the parent directories): .git
```

running `git commit` followed by `cargo build` again cause the build to succeed.

I'm not sure if the bug is cargo's or curl-rust's.

full `cargo build` output: https://gist.github.com/dovreshef/ff4354094ac858c711351a0ec625c58f

**Comment by alexcrichton** [comment]
Oh that's actually a red herring I think, the real error is:

```
Could Not Find C:\Users\****\.cargo\registry\src\github.com-1ecc6299db9ec823\curl-sys-0.2.1\curl\winbuild\LIBCURL_OBJS.inc
Could Not Find C:\Users\****\.cargo\registry\src\github.com-1ecc6299db9ec823\curl-sys-0.2.1\curl\winbuild\CURL_OBJS.inc
thread 'main' panicked at 'fs::remove_dir_all(src.join("curl/builds")) return the error The directory is not empty. (os error 145)', C:\Users\****\.cargo\registry\src\github.com-1ecc6299db9ec823\curl-sys-0.2.1\build.rs:267
```

Do you have some commands available to reproduce this?

**Comment by dovreshef** [comment]
I've reproduced the issue, though it is a bit different.

The steps to reproduce:

1. `cargo new issues121 --bin`.
2. `curl = "0.3.2"` in cargo.toml dependencies.
3. Replace main.rs with one of the examples from the start page.
4.  run `cargo build`.

It will fail with the same error. Re-running `cargo build` again though, without doing anything, will succeed.

Tested on windows 7. `rustc` details:

    Default host: i686-pc-windows-gnu
    
    installed toolchains
    --------------------
    
    nightly-i686-pc-windows-gnu
    nightly-i686-pc-windows-msvc (default)
    
    active toolchain
    ----------------
    
    nightly-i686-pc-windows-msvc (default)
    rustc 1.12.0-nightly (b30eff7ba 2016-08-05)`

**Comment by alexcrichton** [comment]
Hm I wonder, but what does your VS installation look like? Is it relatively standard or is there something custom about it?

**Comment by dovreshef** [comment]
Standard VS2015 installation. 

I've also got the following C++ redistributable components installed: 

![c](https://cloud.githubusercontent.com/assets/5120549/17647337/5f9325ee-61f5-11e6-9e5e-10a91623b16b.PNG)

**Comment by alexcrichton** [comment]
Is there perhaps any concurrent build happening or some other process trying to access these files?

**Comment by dovreshef** [comment]
@alexcrichton not that I could see. I'll try to replicate it in a newly built VM, but that will take a while (a week or so).

**Comment by aidanhs** [comment]
Just had to build twice. First time I got this error:
```
--- stderr
configure: WARNING: Cannot find libraries for IDN support: IDN disabled
configure: WARNING: disabling built-in manual
make: warning: -jN forced in submake: disabling jobserver mode.
make[2]: *** No rule to make target '/tools/frankenlinux/root/.cargo/registry/src/github.com-1ecc6299db9ec823/curl-sys-0.3.12/curl/lib/file.c', needed by 'libcurl_la-file.lo'.  Stop.
make[1]: *** [all] Error 2
make: *** [all-recursive] Error 1
thread 'main' panicked at '
command did not execute successfully, got: exit code: 2
```

**Comment by alexcrichton** [comment]
Enough about the build has changed that I believe this is fixed, so closing.
