### ISSUE TITLE
Use of '`pthread' fails in Windows 32bits

### ISSUE THREAD

**Issue by LeMoussel** [alexcrichton/curl-rust#124]
I come across this error when trying to compile on Windows 32bits. I have MSYS2 installed. It seems that 'pthread' is not supported by MSYS2 / mingw32.

> error: linking with `gcc` failed: exit code: 1
> D:/Applications/msys32/mingw32/bin/../lib/gcc/i686-w64-mingw32/6.1.0/libgcc_eh.a(unwind-dw2-fde.o):(.text+0x1a3): undefined reference to `pthread_mutex_init'
> D:/Applications/msys32/mingw32/bin/../lib/gcc/i686-w64-mingw32/6.1.0/libgcc_eh.a(unwind-dw2-fde.o):(.text+0xfd9): undefined reference to`pthread_once'
> D:/Applications/msys32/mingw32/bin/../lib/gcc/i686-w64-mingw32/6.1.0/libgcc_eh.a(unwind-dw2-fde.o):(.text+0xfe5): undefined reference to `pthread_mutex_lock'
> D:/Applications/msys32/mingw32/bin/../lib/gcc/i686-w64-mingw32/6.1.0/libgcc_eh.a(unwind-dw2-fde.o):(.text+0x10f4): undefined reference to`pthread_once'
> D:/Applications/msys32/mingw32/bin/../lib/gcc/i686-w64-mingw32/6.1.0/libgcc_eh.a(unwind-dw2-fde.o):(.text+0x1100): undefined reference to `pthread_mutex_lock'
> D:/Applications/msys32/mingw32/bin/../lib/gcc/i686-w64-mingw32/6.1.0/libgcc_eh.a(unwind-dw2-fde.o):(.text+0x11cb): undefined reference to`pthread_once'
> D:/Applications/msys32/mingw32/bin/../lib/gcc/i686-w64-mingw32/6.1.0/libgcc_eh.a(unwind-dw2-fde.o):(.text+0x11d7): undefined reference to `pthread_mutex_lock'
> D:/Applications/msys32/mingw32/bin/../lib/gcc/i686-w64-mingw32/6.1.0/libgcc_eh.a(unwind-dw2-fde.o):(.text+0x1239): undefined reference to`pthread_mutex_unlock'
> D:/Applications/msys32/mingw32/bin/../lib/gcc/i686-w64-mingw32/6.1.0/libgcc_eh.a(unwind-dw2-fde.o):(.text+0x1268): undefined reference to `pthread_mutex_unlock'
> D:/Applications/msys32/mingw32/bin/../lib/gcc/i686-w64-mingw32/6.1.0/libgcc_eh.a(unwind-dw2-fde.o):(.text+0x12ef): undefined reference to`pthread_once'
> D:/Applications/msys32/mingw32/bin/../lib/gcc/i686-w64-mingw32/6.1.0/libgcc_eh.a(unwind-dw2-fde.o):(.text+0x12fb): undefined reference to `pthread_mutex_lock'
> D:/Applications/msys32/mingw32/bin/../lib/gcc/i686-w64-mingw32/6.1.0/libgcc_eh.a(unwind-dw2-fde.o):(.text+0x1337): undefined reference to`pthread_mutex_unlock'
> D:/Applications/msys32/mingw32/bin/../lib/gcc/i686-w64-mingw32/6.1.0/libgcc_eh.a(unwind-dw2-fde.o):(.text+0x13f6): undefined reference to `pthread_mutex_unlock'
> D:/Applications/msys32/mingw32/bin/../lib/gcc/i686-w64-mingw32/6.1.0/libgcc_eh.a(unwind-dw2-fde.o):(.text+0x1004): undefined reference to`pthread_mutex_unlock'
> D:/Applications/msys32/mingw32/bin/../lib/gcc/i686-w64-mingw32/6.1.0/libgcc_eh.a(unwind-dw2-fde.o):(.text+0x111f): undefined reference to `pthread_mutex_unlock'
> collect2.exe: error: ld returned 1 exit status

Could there be something I missed in my install?
I cannot find much about this error online except that this function is not on Windows.

**Comment by alexcrichton** [comment]
Thanks for the report! Could you describe how you installed MSYS2 as well as how you installed the gcc compiler? On 32-bit windows there are two variants of compilers, and it looks like the wrong one is being used by accident unfortunately for Rust :(

**Comment by LeMoussel** [comment]
I installed 

- MSYS2 with [MSYS2 installer](https://msys2.github.io/) 
- Rust V1.11.0 Windows (GNU ABI)  with no linker and platform libraries

**Comment by alexcrichton** [comment]
Did you install `gcc` through a MSYS2 package?

**Comment by LeMoussel** [comment]
Yes.

**Comment by alexcrichton** [comment]
Ah a bit of a belated response, but unfortunately the default gcc on msys2 comes with the wrong threading model which will have these problems. The [instructions for Rust itself](https://github.com/rust-lang/rust#building-on-windows) though should suffice in downloading an appropriate compiler.
