### ISSUE TITLE
Panic on Ubuntu 16.04: index out of bounds: the len is 0 but the index is 0

### ISSUE THREAD

**Issue by LukasKalbertodt** [alexcrichton/curl-rust#130]
On StackOverflow someone asked about a panic originating from this crate. I just wanted to notify you:

http://stackoverflow.com/questions/40021037/runtime-error-with-rust-slack-index-out-of-bounds-the-len-is-0-but-the-index-i

**Comment by alexcrichton** [comment]
Thanks for the report! I think this was fixed by https://github.com/alexcrichton/curl-rust/commit/7a8ee68bb897575ad333d606b2415c2cca50139c which I've now published to crates.io (forgot to do so earlier)
