### ISSUE TITLE
Update curl submodule on 02/11 for vulnerability fixes

### ISSUE THREAD

**Issue by mattico** [alexcrichton/curl-rust#131]
https://curl.haxx.se/mail/lib-2016-10/0076.html

> In two weeks time, on Wednesday November 2nd, we will release curl and libcurl 
> 7.51.0 unless something earth shattering happens. 
> This release will bundle no less than _eleven_ security advisories and their 
> associated fixes (unless we get more reported in the time we have left). Each 
> individual security issue will be documented in detail in their own advisories 
> as usual and sent out as separate emails and get documented on the curl web 
> site. Chances are big several of these affects your use of curl. 
> We have never before handled anywhere close to this many security problems in 
> a single release.

**Comment by alexcrichton** [comment]
👍 Thanks for the heads up! I'll be sure to try to update this library very quickly.

**Comment by alexcrichton** [comment]
Ok, this update is now on master.

I'll publish new versions once CI passes
