### ISSUE TITLE
Return value of `curl_sys::curl_global_init` is ignored in `curl::init`

### ISSUE THREAD

**Issue by simias** [alexcrichton/curl-rust#133]
The [documentation](https://curl.haxx.se/libcurl/c/curl_global_init.html) says that "If this function returns non-zero, something went wrong and you cannot use the other curl functions". However the [init](https://github.com/alexcrichton/curl-rust/blob/master/src/lib.rs#L82) function ignores this return value.

I haven't checked the libcurl implementation to see how likely this function is to fail but at the very least maybe curl-rust should panic if it returns non-0?

**Comment by alexcrichton** [comment]
Ah yes that should indeed assert non-0!
