### ISSUE TITLE
Support for curl options?

### ISSUE THREAD

**Issue by tomyan** [alexcrichton/curl-rust#144]
I'd like to make use of https://curl.haxx.se/libcurl/c/CURLOPT_UNIX_SOCKET_PATH.html for making requests over a domain socket. I have tried to use `req.setopt_str(...)`, but that doesn't work as it's private. Is there a way to do this already, or otherwise something you'd appreciate a PR for (pretty new to Rust, so might take a while)? I also couldn't see a way to import the `CURLOPT_UNIX_SOCKET_PATH` constant - maybe that needs to be added to the curl_sys crate?

Thanks

Tom

**Comment by alexcrichton** [comment]
Ah yeah those helpers are just private functions, but no option is left out explicitly! Want to send a PR implementing this option?

**Comment by alexcrichton** [comment]
Unix socket support added in https://github.com/alexcrichton/curl-rust/pull/154, so closing.
