### ISSUE TITLE
Easy::verbose doesn't naively work

### ISSUE THREAD

**Issue by maxdymond** [alexcrichton/curl-rust#146]
The following code does not by default dump out verbose libcurl messages:

```
extern crate curl;

use curl::easy::Easy;

/// Main function
fn main() {
    let mut handle = Easy::new();
    handle.url("https://httpbin.org/ip").unwrap();
    handle.verbose(true).unwrap();
    handle.perform().unwrap();
}
```
The documentation for this function says:

>     /// Configures this handle to have verbose output to help debug protocol
>     /// information.
>     ///
>     /// By default output goes to stderr, but the `stderr` function on this type
>     /// can configure that. You can also use the `debug_function` method to get
>     /// all protocol data sent and received.
>     ///
>     /// By default, this option is `false`.

The problem is that the `perform` method calls `reset_scoped_configuration` underneath the covers, which sets a debug function. By default the debug function silently drops everything.

For posterity, here's an example which restores the native libcurl functionality:
```
extern crate curl;

use std::io::{stderr, Write};
use curl::easy::{Easy, InfoType};

/// Main function
fn main() {
    let mut handle = Easy::new();
    handle.url("https://httpbin.org/ip").unwrap();
    handle.verbose(true).unwrap();
    handle.debug_function(|infotype, data| {
            match infotype {
                InfoType::Text | InfoType::HeaderIn | InfoType::HeaderOut => {
                    stderr().write(data).unwrap();
                }
                _ => {
                    0;
                }
            };
        })
        .unwrap();
    handle.perform().unwrap();
}
```

**Comment by alexcrichton** [comment]
Thanks for the report! I wonder if we could keep a boolean to indicate whether `debug_function` has been set and if it hasn't then we don't reset it. That should solve this issue, right?

**Comment by maxdymond** [comment]
I think that seems pretty sensible, yes.
