### ISSUE TITLE
Allow building statically even if there is a system libcurl

### ISSUE THREAD

**Issue by Timmmm** [alexcrichton/curl-rust#148]
Currently if I want to build a binary that is statically linked to libcurl there is no way to do that if I have a system curl already installed.

Most crates do this by detecting an environment variable, e.g. `OPENSSL_STATIC` or `LIBZ_SYS_STATIC`. I think that's a pretty terrible system to be honest; there should be a global option. But I suppose it is the best we have for now. I suggest adding `CURL_STATIC`.

**Comment by overminder** [comment]
IIRC if you are on Linux and is using [pkgconfig](https://github.com/alexcrichton/pkg-config-rs) to look for libcurl you may just add a `LIBCURL_STATIC=1` environment variable ([see its implementation here](https://github.com/alexcrichton/pkg-config-rs/blob/bd1d464/src/lib.rs#L462)) to force static linking.

**Comment by awakecoding** [comment]
Any update on this? I would like to integrate some Rust code in a C project that already links to a static build of libcurl + mbedtls, it would be great not to duplicate this dependency. In other words, I would like to compile curl-rust against my own custom build of libcurl, given that it is a compatible version built with the right options.

**Comment by alexcrichton** [comment]
@awakecoding for situations like that Cargo allows [overriding build scripts](https://doc.rust-lang.org/cargo/reference/build-scripts.html#overriding-build-scripts)

**Comment by Timmmm** [comment]
I don't have time to update this, sorry!

**Comment by sagebind** [comment]
This should be solved now with the addition of the `static-curl`, yes?

**Comment by alexcrichton** [comment]
I think so!
