### ISSUE TITLE
Json body

### ISSUE THREAD

**Issue by yoni386** [alexcrichton/curl-rust#155]
How to post json bytes for example; {"Username":"root", "Password": 1234}

**Comment by alexcrichton** [comment]
I believe you can do this with either [`Easy::post_body_copy`](https://docs.rs/curl/0.4.6/curl/easy/struct.Easy.html#method.post_fields_copy) or [`Easy::read_function`](https://docs.rs/curl/0.4.6/curl/easy/struct.Easy.html#method.read_function) where it just reads an in-memory buffer (your JSON).

Does that work?

**Comment by alexcrichton** [comment]
Closing as I believe as one or two of those functions will handle your use case, but please let me know if there's still an issue!

**Comment by yoni386** [comment]
Hello Alex,
  
For now I used "handle.post_fields_copy()" and "handle.http_headers()". 
Later on more complicated http.post I will try Easy::post_body_copy or Easy::read_function

        let mut list = List::new();
        list.append("content-type: application/json").unwrap();
        handle.post(true).unwrap();

        let data = format!(r#"{{"UserName":"{}", "Password":"{}"}}"#, &self.user, &self.password);
        handle.post_fields_copy(data.as_bytes());
        handle.http_headers(list).unwrap();

Thank you,

Yoni
