### ISSUE TITLE
the trait `std::fmt::Debug` is not implemented for `curl::easy::Easy`

### ISSUE THREAD

**Issue by Ajacmac** [alexcrichton/curl-rust#159]
I'm trying to figure out this animal called Rust, and tried using 

`let mut easy = Easy::new();
println!("{:?}", easy);`

with the hope of poking around, but it turns out that Debug isn't implemented. I asked around, looking for help, and someone told me that it's recommended to implement Debug, and that I should put in an issue for it. 

Thanks!

**Comment by alexcrichton** [comment]
Thanks for the report!
