### ISSUE TITLE
Add support for --proxy-cacert or --proxy-insecure

### ISSUE THREAD

**Issue by lunatik13** [alexcrichton/curl-rust#160]
Currently it's impossible to use this unix curl example:
`curl -x https://squid.domain.com:443 --proxy-user user:pass https://ifconfig.co --proxy-cacert bundle.crt`
Or maybe i can use sщme available functions ?

**Comment by lunatik13** [comment]
squid.conf
```
https_port $SQUID_EXT_IP:443 cert=/path/to/wild.domain.crt  key=/path/to/wild.domain.key
```
```rust
extern crate curl;

use std::io::{stdout, Write};

use curl::easy::Easy;

fn main() {
    let mut easy = Easy::new();
    easy.proxy("https://squid.domain.com").unwrap();
    easy.proxy_port(443).unwrap();
    easy.proxy_username("user").unwrap();
    easy.proxy_password("pass").unwrap();
    easy.url("https://httpbin.org/ip").unwrap();
    easy.write_function(|data| {
        Ok(stdout().write(data).unwrap())
    }).unwrap();
    easy.perform().unwrap();

    println!("{}", easy.response_code().unwrap());
}
```
Error
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { description: "Peer certificate cannot be authenticated with given CA certificates", code: 60, extra: Some("SSL certificate problem: unable to get local issuer certificate") }', src/libcore/result.rs:868
```

**Comment by alexcrichton** [comment]
I'd definitely love to have support for these! This would probably just involve binding a constant or two and then adding the appropriate functions to access it.

Would you be interested in sending a PR for this functionality? I could certainly help out if needed!

**Comment by alexcrichton** [comment]
You may want to try running `cargo run` inside of the `systest` folder which will validate the value of `CURLOPT_PROXY_CAPATH`, and failing that perhaps you're linking against a version of libcurl itself that doesn't have the option?
