### ISSUE TITLE
Fails to build with VC++ build tools

### ISSUE THREAD

**Issue by Diggsey** [alexcrichton/curl-rust#161]
Fails to find `rc`, on this line:

https://github.com/alexcrichton/curl/blob/651be36a7459015d601c22dc36161c9db60c7a1c/winbuild/MakefileBuild.vc#L497

Presumably with a full MSVC install, `nmake` ensures that `rc` is on the PATH.

**Comment by alexcrichton** [comment]
Do you have more info about this? Do the vc++ build tools not include rc? Are they in a special location? Are you  using 2017? 2015?

**Comment by Diggsey** [comment]
I have the VC++ 2015 build tools installed, in addition to Visual Studio 2017, everything with default settings.

VC++ build tools includes `rc`, but it's part of the windows SDK rather than part of the compiler, so it's not in the same directory as the other compiler tools.

As a work-around, I was able to copy `rc.exe` and the DLL it depends on, into the compiler bins directory.

**Comment by alexcrichton** [comment]
This crate currently relies on gcc-rs to do detection of these tools, so is there something else that needs to be added to `PATH` by gcc-rs? What is the special dir that `rc` is located in? For example is there another path that should be [pushed here](https://github.com/alexcrichton/gcc-rs/blob/88eb0745dd2b4525a8d11961e31c6acd1277a5c3/src/windows_registry.rs#L133)?

**Comment by Diggsey** [comment]
It looks like the issue is here: https://github.com/alexcrichton/gcc-rs/blob/88eb0745dd2b4525a8d11961e31c6acd1277a5c3/src/windows_registry.rs#L273

This checks that a given SDK is "complete" by looking for `kernel32.lib`. My installation has this library, and so it tries to use the windows 10 SDK rather than the windows 8 SDK. However, only the windows 8 SDK includes the required binary `rc.exe`.

I'm afraid I don't know what the correct checks should look like, to ensure that a given SDK is complete. Maybe @retep998 can help?

**Comment by retep998** [comment]
What could work as a solution is finding the Windows SDK for bin purposes independently of finding the Windows SDK for library purposes.

**Comment by brson** [comment]
I will include a fix for it in my gcc-rs patch for vs2017.

**Comment by alexcrichton** [comment]
In theory closed by https://github.com/alexcrichton/gcc-rs/pull/160, but if it's still her ejust let me know!
