### ISSUE TITLE
Reinstate keepalive functions?

### ISSUE THREAD

**Issue by maxdymond** [alexcrichton/curl-rust#162]
In commit https://github.com/alexcrichton/curl-rust/commit/95a2686c8f86bd00598feb32ba5d4359e7c2cd16 the tcp keepalive functions (amongst many other functions) were disabled due to CI not passing.

Can these functions now be reinstated? As the HTTP2 work showed, CI can ignore things if the underlying curl library / curl header file doesn't understand them.

**Comment by alexcrichton** [comment]
Certainly! They were just removed at the time as they didn't instantly work and I didn't have time to get back around to them. Would you be interested in trying to re-enable them via a PR? I can help out if you've got any questions!

**Comment by alexcrichton** [comment]
Ah let's see how a PR goes -- https://github.com/alexcrichton/curl-rust/pull/163

**Comment by maxdymond** [comment]
Thanks! Sorry for not getting a PR done, I was busy with other stuff.

**Comment by alexcrichton** [comment]
No worries! Lemme know if there's any more problems!
