### ISSUE TITLE
General question in which conditions a vector lives only in the stack? "Collecting headers to a stack local vector"

### ISSUE THREAD

**Issue by yoni386** [alexcrichton/curl-rust#165]
General question in which conditions a vector lives only in the stack? "Collecting headers to a stack local vector" https://docs.rs/curl/0.4.6/curl/easy/struct.Easy.html#method.header_function
http://mibpaste.com/r7og1n

**Comment by alexcrichton** [comment]
Oh  this basically just has to do with lifetimes in Rust. The `Easy::header_function` requires a closure with `'static` which means it can't have any borrowed references, but the `Transfer::header_function` relaxes this restriction.

**Comment by alexcrichton** [comment]
Closing for now
