### ISSUE TITLE
vcpkg-rs breaks cargo install of apps using curl-sys for msvc abi builds

### ISSUE THREAD

**Issue by mcgoo** [alexcrichton/curl-rust#171]
Can you help check my thinking here? TL;DR is vcpkg probably needs to be off by default.

I should have seen this coming, but the original intent was to link statically by default, which turned out not to be possible because the static libraries in Vcpkg require a static CRT. 

The vcpkg-rs build helper will link to dlls in a Vcpkg installation in a typical build. It finds an installation if `VCPKG_ROOT` in the user's env points to it. (This is something that some percentage of VC++ users are going to have set, it's not specific to the build helper.) `cargo install` of anything using curl, libssh2, zlib is not going to work for them since the dll versions are chosen in preference to the internal statically linked versions. At least one person, @pravic has hit this in the day that curl-sys 0.3.12 has been out. 

The only solutions I can think of are:
1) make vcpkg-rs a no-op unless another variable is set (`VCPKGRS_ENABLE=1`?)
2) rip the support out of curl-sys and friends

I'll push out a vcpkg-rs 0.2.2 that requires an explicit enable unless you have any better suggestions.

Regarding option 2, can you comment on whether a build like this is possible:
```
(rust-exe+static curl) -> (some.dll) -> (curl.dll)
```
because if it is, there might not be a whole lot of point in having the support in curl-sys at all? It seems like you would want to be able to use an external curl.dll but if there is no upside, maybe it would be better to just not do it.

It's probably not a huge deal to make it opt-in now that it can't be static by default. A big part of the point was to try to make `cargo install` easier. If someone has to set `RUSTFLAGS` for static CRT, it's not a big deal to set another variable also.

Thanks and sorry for the extra work.

cc @retep998 because Windows

**Comment by alexcrichton** [comment]
Ah yeah I'm not too familiar with vcpkg and the inner workings there, so I'm fine to go along with whatever you think is best. It seems reasonable to me though to try to turn off vcpkg by default in "reasonable situations". Presumably the vcpkg crate could detect whether it's compiling with the static crt and enable/disable itself accordingly?

**Comment by ras0219-msft** [comment]
We might be able to add `*-windows-static-md` triplets which make static lib + dynamic runtime more accessible out-of-the-box, though it still wouldn't be the default for `vcpkg install <X>`.

How does pkg-config get around this issue -- doesn't it also conflict with the internal statically linked versions?

Also, I'm still a bit fuzzy on why shared libraries cause such a problem... is it because the loader doesn't find them when you launch your compiled rust application and cargo doesn't have a post-build step to copy them to the output folder?

**Comment by pravic** [comment]
> and cargo doesn't have a post-build step to copy them to the output folder?

No, vcpkg-rs is able to copy DLLs to cargo's output.

**Comment by mcgoo** [comment]
@ras0219-msft, the `cargo install` mechanism is basically "build an executable and copy it to $HOME/.cargo/bin". At this point it doesn't drag along any dependent libraries.

I think it typically works for pkg-config even if it chooses dynamic libraries because the libs are in a location that the loader will find, like /usr/bin or /usr/local/bin. If you are building your own customized version of curl you're probably not going to be surprised by having to set your library search path.

**Comment by mcgoo** [comment]
By the way, the Vcpkg/vcpkg-rs dynamic linking case works really well with `cargo test` etc, it just can't be on by default right now because of the poor interaction with `cargo install`.

**Comment by ras0219-msft** [comment]
Ah ok, so pkg-config (on win/msvc) would have this exact same issue then?

There might be a way to generate an application manifest[1] (which can be put inside the exe!) to redirect the loader[2] -- I _think_ it has similar capabilities as RPATH on other platforms, though I'll need to consult some experts ;).

[1] https://msdn.microsoft.com/en-us/library/windows/desktop/aa374191(v=vs.85).aspx
[2] https://msdn.microsoft.com/en-us/library/windows/desktop/ms682586(v=vs.85).aspx

**Comment by mcgoo** [comment]
This is all way off topic, but...

I'm getting out of my area, but I think that if you are a rust -pc-windows-gnu toolchain user and you build from a command prompt you will tend to get the built-in version and if you build from an msys2 prompt you will get the builtin version unless you have installed stuff with `pacman` in which case your paths are likely to be good to find the shared libraries because you are running under msys2. 

I'm all ears about the application manifest thing. In particular it would be useful to achieve the same result as RPATH=$ORIGIN/../lib which some of the rust toolchain binaries have set. I was not able to see how to do that.

**Comment by mcgoo** [comment]
I just published vcpkg 0.2.2 which now requires `VCPKGRS_DYNAMIC` to be set in order to link dynamically. This should stop Vcpkg users getting "DLL not found" after `cargo install`ing things that depend on curl-sys or libz-sys.
