### ISSUE TITLE
curl-sys build fails on appveyor with apparent race

### ISSUE THREAD

**Issue by danburkert** [alexcrichton/curl-rust#174]
Hi, I'm in the process of adding appveyor coverage to a project which depends on `curl` in different modules as both a build-dependency and a normal dependency.  The build fails ([full log](https://ci.appveyor.com/project/danburkert/prost/build/1.0.9/job/s03tjivb8j7822on)), I think the relevant bit is here:

> ..\lib\netrc.c: fatal error C1041: cannot open program database 'C:\Users\appveyor\.cargo\registry\src\github.com-1ecc6299db9ec823\curl-sys-0.3.13\curl\winbuild\vc140.idb'; if multiple CL.EXE write to the same .PDB file, please use /FS

Since this smelled like a race condition, I tried adding `-j1` to the build, and it seems to succeed consistently now.  Before it would fail consistently.  I tried to make my appveyor.yml as close to curl's, except that I'm only using the default targets.  Happy to provide more info on request.

**Comment by alexcrichton** [comment]
Oh dear sounds bad! That looks like it's spraying build files into the source tree which is definitely not intended.

I've opened https://github.com/alexcrichton/curl-rust/pull/175 to test out a fix for this, if that's goes green mind testing that on CI as well to confirm it fixes the issue?

**Comment by danburkert** [comment]
That seems to have done the trick, thanks @alexcrichton!

https://github.com/danburkert/prost/commit/a8e206c3eee37db43998048e81b618b84f0a295f
https://ci.appveyor.com/project/danburkert/prost/build/1.0.16

**Comment by alexcrichton** [comment]
Thanks for testing! I've now merged https://github.com/alexcrichton/curl-rust/pull/175
