### ISSUE TITLE
-F (--form) to upload files using file-path.

### ISSUE THREAD

**Issue by rmnoff** [alexcrichton/curl-rust#182]
Hello,
at the time I am working on the IPFS API wrap for Rust and I am using curl-rust to emulate cURL requests. 
As my next command I need to upload a file, using it's path as -F parameter
`curl -F file=@myfile "http://localhost:5001/api/v0/add?recursive=false"`
where @myfile is path to file.

Is it possible right now? Or is it not implemented?

**Comment by alexcrichton** [comment]
I think https://docs.rs/curl/0.4.8/curl/easy/struct.Part.html#method.file_content may be what you're looking for?

**Comment by rmnoff** [comment]
Still don't get it.. How can I use Part? Can you provide me an example..? It would be great!

**Comment by rmnoff** [comment]
Thank you!
Now it can be closed 👍

**Comment by rmnoff** [comment]
Actually I found one more interesting thing: at symbol. Without it IPFS can't find file type. Trying to find out how I can solve it.

**Comment by alexcrichton** [comment]
Ok glad that works! What do you mean with IPFS, though?
