### ISSUE TITLE
Build failure with MinGW

### ISSUE THREAD

**Issue by Bobo1239** [alexcrichton/curl-rust#189]
`cargo build` fails with
```
failed to open E:/Development/Rust/curl-rust/curl-sys/curl/lib/E:/Development/Rust/curl-rust/curl-sys/curl/lib/amigaos.c at E:/Development/Rust/curl-rust/curl-sys/curl/lib/checksrc.pl line 259.
```
using MinGW 64-bit (msys2).

Could we just remove (or restrict to msvc) [this check](https://github.com/alexcrichton/curl-rust/blob/f4a6e2fbf8885216f2d942f86e291cea68c78a56/curl-sys/build.rs#L39)? If I comment that out my build succeeds.

**Comment by alexcrichton** [comment]
Can you gist the full log of the build failure?

**Comment by Bobo1239** [comment]
Sure: https://gist.github.com/Bobo1239/bde296b5d1251b4634426bc2b68046c1

**Comment by alexcrichton** [comment]
Ah the bug is [here](https://github.com/alexcrichton/curl-rust/blob/f4a6e2fbf8885216f2d942f86e291cea68c78a56/curl-sys/build.rs#L245-L252), it only handles builds on `C:\`, not on `E:\`, alas!
