### ISSUE TITLE
Expose trace()

### ISSUE THREAD

**Issue by martinlindhe** [alexcrichton/curl-rust#197]
While debugging, I would like to have trace enabled (as `--trace -` on curl command line),
similar to how verbose is enabled in curl-rust today, https://github.com/alexcrichton/curl-rust/blob/f4a6e2fbf8885216f2d942f86e291cea68c78a56/src/easy/handle.rs#L137

**Comment by alexcrichton** [comment]
Thanks for the report! Do you know the option in libcurl that this corresponds to?

**Comment by martinlindhe** [comment]
Not sure, looking into it - first impression seems to be that there isnt any trace in libcurl directly, but one would implement it with a callback.

Not sure I want to request this feature anymore if it is not exposed in the underlying API. (I'll ask over at curl about this).

There is an example here: https://curl.haxx.se/libcurl/c/CURLOPT_DEBUGFUNCTION.html (or https://github.com/curl/curl/blob/87501e57f1c166cb250111af54e0470ab8b2099c/docs/examples/debug.c)

Something like

```
    curl_easy_setopt(curl, CURLOPT_DEBUGFUNCTION, my_trace);
 

static
int my_trace(CURL *handle, curl_infotype type,
             char *data, size_t size,
             void *userp)
{
  const char *text;
  (void)handle; /* prevent compiler warning */
  (void)userp;
 
  switch (type) {
  case CURLINFO_TEXT:
    fprintf(stderr, "== Info: %s", data);
  default: /* in case a new one is introduced to shock us */
    return 0;
 
  case CURLINFO_HEADER_OUT:
    text = "=> Send header";
    break;
  case CURLINFO_DATA_OUT:
    text = "=> Send data";
    break;
  case CURLINFO_SSL_DATA_OUT:
    text = "=> Send SSL data";
    break;
  case CURLINFO_HEADER_IN:
    text = "<= Recv header";
    break;
  case CURLINFO_DATA_IN:
    text = "<= Recv data";
    break;
  case CURLINFO_SSL_DATA_IN:
    text = "<= Recv SSL data";
    break;
  }
 
  dump(text, stderr, (unsigned char *)data, size);
  return 0;
}
```

**Comment by martinlindhe** [comment]
https://github.com/curl/curl/issues/2283

**Comment by martinlindhe** [comment]
Not sure this is worth persuading. An api won't become available, so an implementation in the consumer (curl-rust) would be needed, and that could drift from the curl version in the future.

Feel free to close this issue if you agree

**Comment by alexcrichton** [comment]
I believe you can already [set the debug function](https://docs.rs/curl/0.5.0/curl/easy/struct.Easy.html#method.debug_function), turn on [verbose](https://docs.rs/curl/0.5.0/curl/easy/struct.Easy.html#method.verbose), and get that output?

The debug function is even [set by default](https://github.com/alexcrichton/curl-rust/blob/master/src/easy/handler.rs#L303-L318) so all you'd need to do is turn `verbose` on

**Comment by martinlindhe** [comment]
I didn't mean to post that code as an implementation, it is just from their docs as example on how one would implement such feature in the c api.

You can see the different modes from the command line with .verbose() as `-v` and this proposed mode instead as `--trace -`

**Comment by alexcrichton** [comment]
Ah ok, were there changes that we should do in this library to match libcurl?

**Comment by martinlindhe** [comment]
No as the debug function is in curl-rust, a user should be able to implement this. I'll close this for now.
