### ISSUE TITLE
"Getting Started" code fails with when requesting large pages on Windows

### ISSUE THREAD

**Issue by jason-watkins** [alexcrichton/curl-rust#200]
When requesting a large web page using the code in the readme, I get an error on Windows. When running the code attached below, I get this error: `Error { description: "Failed writing received data to disk/application", code: 23, extra: Some("Failed writing body (8192 != 15674)") }`. I do not get an error when running the same request on Arch. Unfortunately I'm fairly new to Rust and I'm not sure how to work around this error on Windows. Can anyone provide some insight into why this occurs and how best to fix it?

Complete code I am running:
```rust
//main.rs
extern crate curl;

use std::io::{stdout, Write};

use curl::easy::Easy;

fn main() {
    let mut easy = Easy::new();
    easy.url(
        "https://www.kcrw.com/music/shows/morning-becomes-eclectic/latest-show",
    ).unwrap();
    easy.write_function(|data| Ok(stdout().write(data).unwrap()))
        .unwrap();
    easy.perform().unwrap();

    println!("{}", easy.response_code().unwrap());
}
```

```
#cargo.toml
[package]
name = "kcrw-rs"
version = "0.1.0"
authors = ["Jason Watkins <jason-watkins@outlook.com>"]

[dependencies]
curl = "0.4.11"
```

System details:
Windows 10 Pro Version 1709
Arch with all packages updated
Both systems are running the latest version of rust stable.

**Comment by alexcrichton** [comment]
Thanks for the report!

**Comment by ccqpein** [comment]
Still get this issue, is there a way to fix it?

**Comment by sagebind** [comment]
Are you using `write_all`?

The original problem in this case is that the example code was using just `write`, but you can't assume that `write` will write the entire buffer in a single call, resulting in an error being propagated to curl. The examples now use `write_all` which is the correct way to handle the write callback.

**Comment by ccqpein** [comment]
Let me try `write_all`, I am actually running the `extend_from_slice` code of README.

**Comment by sagebind** [comment]
Are you sure the error is the same as the one in this case description?

**Comment by ccqpein** [comment]
It is the same error code from libcurl and I think because I screwed up write_all in closure of `write_fuction`. Now there is no problem at all. Sorry for bothering you guys. 🙏
