### ISSUE TITLE
Release curl-sys 0.4.2 and curl 0.4.12 to publish working minimal dependency versions

### ISSUE THREAD

**Issue by klausi** [alexcrichton/curl-rust#207]
Coming from https://github.com/rust-lang/cargo/pull/5275

We need to get new versions of the crates out so that other crates can rely on the fixed minimum versions from #206

**Comment by matklad** [comment]
If we want to do a release due to version, then we might want to update winapi to 0.3 as well: https://github.com/alexcrichton/curl-rust/pull/208

**Comment by alexcrichton** [comment]
Done!
