### ISSUE TITLE
nghttp2 on Ubuntu

### ISSUE THREAD

**Issue by 1tgr** [alexcrichton/curl-rust#211]
I'm building on Ubuntu, where libcurl currently has to be compiled from source in order to include nghttp2 support: https://askubuntu.com/a/884900

I installed libnghttp2-dev per https://gist.github.com/tachyons/3adcbbe10e645feb069dc4f49406fde1

Now I'm having a hard time telling build.rs to use the libnghttp2 installed on the system. I think it wants me to set `DEP_NGHTTP2_ROOT=<somewhere that has a lib/pkgconfig subdir>`. But I have /usr/lib/x86_64-linux-gnu/pkgconfig/libnghttp2.pc, so build.rs is never going to be able to find it.

Really I want build.rs to run libcurl `configure --with-nghttp2`, not `configure --with-http2={}`.

Is there a way to get build.rs to pick up the system-wide copy of libnghttp2 I installed using `apt-get`?

**Comment by alexcrichton** [comment]
There's some [support for this](https://github.com/alexcrichton/curl-rust/blob/8b41ad05c8af8c17792bf8020d0e5c9d06bd6a76/curl-sys/build.rs#L170-L174) but it's not well documented nor automatically picked up. I'd be totally down for adding better support though!

**Comment by mati865** [comment]
FWIW beginning with Ubuntu 18.04 libcurl comes with [nghttp2 enabled](https://packages.ubuntu.com/bionic/libcurl4).

**Comment by sagebind** [comment]
I think this is solved now with the latest version, which offers a `http2` Cargo feature that defaults to disabled. Enabling the feature should cause the bundled libcurl to be used with nghttp2 if the system libcurl doesn't include nghttp2.

**Comment by alexcrichton** [comment]
Indeed!
