### ISSUE TITLE
curl-sys 0.4.9 was a breaking change? no out/bin/curl-config

### ISSUE THREAD

**Issue by bedax** [alexcrichton/curl-rust#235]
i was relying on curl-sys outputting `DEP_CURL_ROOT/bin/curl-config` but now it's not being produced. it seems that 0.4.8 used the `configure` script to build curl, whereas 0.4.9 seems to use a custom `cc` command.

Either way, it would be good to have access to either a built curl-config or the built pkg-config files. Any recommendations?

**Comment by alexcrichton** [comment]
Oh dear sorry about that! Since most dependencies don't need `curl-config` I think I'd prefer if it were an opt-in feature rather than always on, but seems fine to add back! (also seems fine to set up pkg-config files as well)

**Comment by bedax** [comment]
Ah good stuff, well it would be nice to see it back, but I've set the dependency to 0.4.8 so all's well. Thanks for everything @alexcrichton !
