### ISSUE TITLE
Help with calling curl commands

### ISSUE THREAD

**Issue by jicee13** [alexcrichton/curl-rust#241]
New to rust here and was hoping someone could offer some guidance...

All I'm trying to do is make a couple of curl requests via Firebase's rest API. I'm trying to [POST](https://firebase.google.com/docs/reference/rest/database/#section-post) and [PUT](https://firebase.google.com/docs/reference/rest/database/#section-put).

As stated in the firebase docs linked above, a curl POST is as simple as:
```
curl -X POST -d '{"user_id" : "jack", "text" : "Ahoy!"}' 
'https://[PROJECT_ID].firebaseio.com/message_list.json'
```

And a PUT is just:
```
curl -X PUT -d '{ "first": "Jack", "last": "Sparrow" }'
'https://[PROJECT_ID].firebaseio.com/users/jack/name.json'
```
Following the docs I tried doing this, but had no luck. Any suggestions?
```
let mut data = "this is the body".as_bytes();
let mut easy = Easy::new();
easy.url("https://[PROJECT_ID].firebaseio.com/users/jack/name.json").unwrap();
easy.post(true).unwrap();
easy.post_field_size(data.len() as u64).unwrap();

let mut transfer = easy.transfer();
transfer.read_function(|buf| {
        Ok(data.read(buf).unwrap_or(0))
    }).unwrap();
transfer.perform().unwrap();
```

**Extra:** What if I wanted to post a json like such?
`let mut test_data = format!(r#"{{"url": "{}", "category": "{}"}}"#, "https://google.com", "category");`

**Comment by alexcrichton** [comment]
I might recommend the [`verbose`](https://docs.rs/curl/0.5.0/curl/easy/struct.Easy2.html#method.verbose) setting to help debug curl itneractions, and you may also want to try [`post_fields_copy`](https://docs.rs/curl/0.5.0/curl/easy/struct.Easy2.html#method.post_fields_copy) which I've had some better luck with in the past. You'll also want to use [`write_function`](https://docs.rs/curl/0.5.0/curl/easy/struct.Easy.html#method.write_function) on the `transfer()` to read the response. 

Does that help track this down? (new examples for this repo would be very much appreciated!

For PUT I think you'd do most of the above and then set [`custom_request`](https://docs.rs/curl/0.5.0/curl/easy/struct.Easy2.html#method.custom_request)

**Comment by alexcrichton** [comment]
I'm going to close this since I believe it's all covered.
