### ISSUE TITLE
curl timings

### ISSUE THREAD

**Issue by bemazo** [alexcrichton/curl-rust#245]
I have an easy script to measure timings with cUrl

```
use curl::easy::Easy;
fn main() {
    let mut easy = Easy::new();
    easy.url("https://www.google.com/").unwrap();
	
    easy.perform().unwrap();
    println!("total-time {:?}", easy.total_time().unwrap());

}
```
on my mac I got this result which is correct

`total-time 299.692ms`

on my server I got this

`total-time 0ns`

I tried a lot with casting into different units, no success

If I do the same with curl directly on the server everything is OK.

Has anybody an idea what happend between mac und linux server?

**Comment by alexcrichton** [comment]
Thanks for the report! This crate, however, is largely just the bindings for curl, and bugs/questions about the usage of libcurl itself should go upstream.
