### ISSUE TITLE
verbose option is ignored?

### ISSUE THREAD

**Issue by dmilith** [alexcrichton/curl-rust#248]
I tried Easy and Easy2 with .verbose(false).. but I still have output from each request like with curl --verbose. Is there a way to tell Easy to use NON-verbose mode?

**Comment by alexcrichton** [comment]
Hm so in theory `.verbose(false)` is how this is turned off, although I remember there being at least one option involved with trying to get verbose logs, although looking through the docs I can't quite find it. Do you have a code snippet to share though which can reproduce this?

**Comment by dmilith** [comment]
It feels like it's related to lto=thin / incremental compilation on my box. I did clean and it worked.
