### ISSUE TITLE
support more ssl versions

### ISSUE THREAD

**Issue by guanqun** [alexcrichton/curl-rust#252]
I see that tlsv1.1 and tlsv1.2 are commented out in the code, see the following line:

https://github.com/alexcrichton/curl-rust/blob/cf4982390b9a10dffd94f82f7b40ab073ad2c2f9/src/easy/handler.rs#L484

any specific reason? I'd like to extend this SslVersion to support more versions. If you're OK, I can help send a simple PR.

**Comment by alexcrichton** [comment]
I think that was jut an artifact of when they were first added, should be fine to uncomment now!

**Comment by guanqun** [comment]
Thanks for the clarification, I've now created a PR to uncomment these enums and added a Tlsv13 too. Please help review. Thanks.

**Comment by guanqun** [comment]
Thanks for the merge, can we bump a version for this small feature?

**Comment by alexcrichton** [comment]
Sure! I noticed though that CI is failing on master, would you be willing to take a look at that? (I think it's caused by this PR)

**Comment by guanqun** [comment]
Sure! I checked the error log:

```
cargo:warning=             static const CURLoption __test_const_CURL_SSLVERSION_TLSv1_3_val = CURL_SSLVERSION_TLSv1_3;
cargo:warning=                                                                                ^
cargo:warning=cc1: error: unrecognized command line option "-Wno-address-of-packed-member" [-Werror]
cargo:warning=cc1: all warnings being treated as errors
exit code: 1
```

So it's due to the TLSv1_3 being not defined. I'm guessing that on that docker image, the curl header/library is too old.

Notice that `Dockerfile-linux64-curl` uses ubuntu 14.04 while `Dockerfile-linux64` uses ubuntu 16.04 and 16.04's version runs well for systest, see the below log:
https://travis-ci.com/alexcrichton/curl-rust/jobs/179317628

So I'd suggest upgrading `Dockerfile-linux64-curl` to use Ubuntu 16.04. If you agree this is a good move, I can create a simple PR.

**Comment by alexcrichton** [comment]
That makes sense! We've got a [number of other cases](https://github.com/alexcrichton/curl-rust/blob/ce920a4f17eea119255ee8305ae7c29f615e778e/systest/build.rs#L70-L109) of constants like that, so I think this'd just need to be added to that list?
