### ISSUE TITLE
GET + data changes to POST

### ISSUE THREAD

**Issue by elbaro** [alexcrichton/curl-rust#254]
```rust
let mut payload = ...as_bytes();
let mut easy = curl::easy::Easy::new();
easy.unix_socket("..").unwrap();
easy.url(url).unwrap();
match method {
	"put" => easy.put(true).unwrap(),
	"get" => easy.get(true).unwrap(),
	"delete" => easy.custom_request("DELETE").unwrap(),
	"post" => easy.post(true).unwrap(),
	_ => unimplemented!(),
}

easy.post_field_size(payload.len() as u64);
...
transfer
.read_function(|buf| Ok(payload.read(buf).unwrap()))
.unwrap();
```

`curl-rust` change my GET request to POST. I used GET because the operation is read-only. This is possible with command-line curl like this:
https://stackoverflow.com/questions/21326397/curl-get-request-with-json-parameter

Also post_field_size may be better named, since the method can be other than POST.

**Comment by sagebind** [comment]
This is not a fault with this crate, this is how libcurl behaves: https://github.com/curl/curl/blob/master/lib/setopt.c#L521-L614. Setting any post fields changes the request method to `POST`. If you really must do this, then setting the request method _after_ you set your POST fields should work.

---

> I used GET because the operation is read-only.

Maybe the API you're calling isn't up to you, but this is against [the HTTP spec](https://tools.ietf.org/html/rfc2616#section-4.3):

> [...] if the request method does not include defined semantics for an entity-body, then the message-body SHOULD be ignored when handling the request.

The request body on a GET request should be ignored by the server.

**Comment by elbaro** [comment]
Thanks. I found this answer:
https://stackoverflow.com/questions/978061/http-get-with-request-body

`easy.get(true)` at the last resets the payload, which conforms to the spec.
