### ISSUE TITLE
libcurl-sys fails to build (undefined reference) on Windows GNU on Appveyor.

### ISSUE THREAD

**Issue by XAMPPRocky** [alexcrichton/curl-rust#257]
## Error
```
undefined reference to `_imp____acrt_iob_func'
```

## Logs
[Appveyor logs](https://ci.appveyor.com/project/Aaronepower/tokei/builds/23323537/job/f5rlhmr55hjlap9d#L181)

**Comment by yorodm** [comment]
Did a little research on this topic and found [this issue](https://github.com/alexcrichton/curl-rust/issues/239), after that I went and changed my .cargo/config
```
[target.x86_64-pc-windows-gnu]
linker = "c:/msys64/mingw64/bin/gcc.exe"
ar = "c:/msys64/mingw64/bin/ar.exe"

[target.i686-pc-windows-gnu]
linker = "c:/msys64/mingw32/bin/gcc.exe"
ar = "c:/msys64/mingw32/bin/ar.exe"
```
I hoped that would work but it doesn't. Any insights?

**Comment by alexcrichton** [comment]
This is an unfortunate interaction with `gcc.exe` distributed by Rust itself. You'll want a solution like @yorodm, you'll want to uninstall the `rust-mingw` component, or you'll want to use an MSVC host toolchain.
