### ISSUE TITLE
URL using bad/illegal format or missing URL

### ISSUE THREAD

**Issue by wahid** [alexcrichton/curl-rust#259]
I came across an issue when I try to post data it gives the error: 

`
Error {
    description: "URL using bad/illegal format or missing URL",
    code: 3,
    extra: None
}
`

When I post the following

`let data = format(r#"type={}"#, "-1");`
`easy.post_fields_copy(data.as_bytes()).unwrap();`

but when I post the following it works

`let data = format(r#"type={}"#, "1");`
`easy.post_fields_copy(data.as_bytes()).unwrap();`

**Comment by mauri870** [comment]
@wahid Can you please explain how did you solve this? Thanks in advice.
