### ISSUE TITLE
Mark setopt_* functions as pub and unsafe.

### ISSUE THREAD

**Issue by Jezza** [alexcrichton/curl-rust#272]
I recently found myself needing to toggle `DIRLISTONLY`, and found no corresponding method.

I think it would be great if we could just quickly bypass the need to have a method while testing some stuff.

**Comment by Jezza** [comment]
It might even be possible to hide it behind a feature...

**Comment by alexcrichton** [comment]
Thanks for the report! I would personally prefer to not commit to this though as part of the public interface. Instead the raw `CURL` handle I believe is exposed and raw methods can be called on that, otherwise PRs are always welcome to bind more options!

**Comment by Jezza** [comment]
Oh, you're completely right.
I missed the `raw` method.

For those that find this in a search:
https://docs.rs/curl/latest/curl/easy/struct.Easy2.html#method.raw


Also a small observation, it looks like one would have to also declare `curl-sys` as a dependency as `curl`, doesn't reexport it.
