### ISSUE TITLE
Need to Be able to borrow an Easy2 from a Multi

### ISSUE THREAD

**Issue by njaard** [alexcrichton/curl-rust#273]
When a transfer is in progress, once you get the headers, but before the payload is received, there's no way to call functions such as `Easy2::response_code()`. This is because `Multi` takes the `Easy2` object and then there's no way to access it.

I suppose simply adding something like `fn Easy2Handle::get(&self) -> { &self.easy }` would be sufficient and safe.

**Comment by njaard** [comment]
Actually, it needs to return a `&mut` because most of the accessors in `Easy2` are `&mut self`

**Comment by alexcrichton** [comment]
Indeed seems like something that access should be provided to! My main concern here is safety to ensure that we're not violating any invariant that libcurl expects us to uphold. For example calling `.perform()` on the `Easy` may cause issues... In any case at the very least it seems reasonable to mirror reasonable things to access onto `Easy2Handle` and such.

**Comment by sagebind** [comment]
I need this now too. I might have some time this week to work on this.

**Comment by sagebind** [comment]
I also wonder if there's a better way of describing the restriction on `perform` than we are currently doing. Maybe using a type state pattern:

```rust
pub struct Easy2<H: Handler, P> {
    // ...
}

pub struct Perform;

// Always starts out Perform
impl<H: Handler> Easy2<H, Perform> {
    fn new(handler: H) -> Easy2<H, Perform> {
        // ...
    }
}

// anything
impl<H, P> Easy2<H, P> {
    // Normal operations...
}

// where P = Perform
impl<H> Easy2<H, Perform> {
    fn perform(&self) -> Result<(), Error> {
        // ...
    }
}

unsafe impl<H> !Send for Easy2<H, Multi> {
    // Can't Send when attached to a multi handle
}

impl Multi {
    fn add2<H>(&self, easy: Easy2<H, Perform>) -> Result<Easy2<H, Multi>, MultiError> {
        // Change type of P from Perform to Multi
    }
}
```

These would be breaking changes of course, and I'm not sure if changing the API for this would be worth the breakage.

**Comment by alexcrichton** [comment]
Hm yeah I think the extra type parameter may be a bit overkill for a use case like this, but perhaps we could just provide an unsafe accessor for the underlying handle and document that the unsafety has to do with reentrancy?
