### ISSUE TITLE
Undefined reference to symbol 'SHA1@@OPENSSL_1_1_0' on updating curl

### ISSUE THREAD

**Issue by mosypov** [alexcrichton/curl-rust#281]
After updating curl via cargo I got linking error when running `cargo build --release
```
  = note: /usr/bin/ld: /path1/path2.rlib(mylib.mylib.3bvqi7pi-cgu.0.rcgu.o): undefined reference to symbol 'SHA1@@OPENSSL_1_1_0'
          /usr/bin/ld: /usr/lib/libcrypto.so.1.1: error adding symbols: DSO missing from command line
          collect2: error: ld returned 1 exit status
``` 
Updated versions:
```
$ cargo update -p curl
    Updating crates.io index
    Updating curl v0.4.17 -> v0.4.22
    Updating curl-sys v0.4.11 -> v0.4.20
```
openssl dep: `openssl-sys 0.9.48`
Local openssl: `OpenSSL 1.1.1c  28 May 2019`

Piece of code that most likely fails:
```rust
extern "C" {
    pub fn SHA1(d: *const c_uchar, n: size_t, md: *mut c_uchar) -> *mut c_uchar;
}
```

When linking statically openssl on other machines it works

**Comment by mosypov** [comment]
So I've just accidentally fixed this just by adding `extern crate openssl_sys;` to the lib.rs. So this line brings openssl_sys to linker, still can't get why this worked well before

**Comment by alexcrichton** [comment]
Linking is pretty tricky, but yes if you're using the symbol you need to declare the library, and that should fix things.
