### ISSUE TITLE
FromUtf8Error

### ISSUE THREAD

**Issue by linkwik** [alexcrichton/curl-rust#298]
There is no coding error in stdio mode, and FromUtf8Error will appear when writing the text. How should I solve it

**Comment by alexcrichton** [comment]
This is unfortunately a pretty cryptic bug report, could you expand on what you're seeing, perhaps with example code and steps of how to reproduce?

**Comment by linkwik** [comment]
```
use std::io::{stdout, Write};
use curl::easy::Easy;

fn main() {
    let mut dst = Vec::new();
    let mut easy = Easy::new();
    easy.url("https://www.rust-lang.org/").unwrap();

    let mut transfer = easy.transfer();
    transfer.write_function(|data| {
        stdout().write_all(data).unwrap();
        dst.extend_from_slice(data);
        Ok(data.len())
    }).unwrap();
    transfer.perform().unwrap();
}
```

target: https://www.qq.com

**Comment by alexcrichton** [comment]
Ah ok, in that case I don't think that this is a bug with this crate but rather with writing raw data to stdout, so I'm going to closethis.
