### ISSUE TITLE
CURL("Error in the HTTP2 framing layer")

### ISSUE THREAD

**Issue by DevQps** [alexcrichton/curl-rust#312]
Hello all,

I am using isahc which depends on this library for doing HTTP calls. When building a Certificate Transparency Log scraper I keep receiving `Curl("Error in the HTTP2 framing layer")` every once in a while.

I construct an (Isahc) HTTP client and do an HTTP request every 5 seconds. After a while (between 10 and 30 minutes) I get the error and any subsequent request return the same error. When I construct a new HTTP client the error goes away but pops up after a while again. I have set the TCP timeout to 30 seconds and I am using the latest version of curl.

Any information on what the problem here can be?

**Comment by alexcrichton** [comment]
I don't know much myself, but I suspect this is just a normal error to retry connections on and/or gracefully recover from. I'd recommend posting examples upstream to `curl` itself for more info about where this comes from and what might be causing it.
