### ISSUE TITLE
Enable FTP protocol support in bundled libcurl

### ISSUE THREAD

**Issue by ebarnard** [alexcrichton/curl-rust#322]
Could we enable FTP support when building the bundled curl version, or at least support it via feature flag?

**Comment by ebarnard** [comment]
See #321 for my motivation.

**Comment by sagebind** [comment]
A feature flag to enable it sounds pretty reasonable.

**Comment by alexcrichton** [comment]
I would prefer to continue to opt-out by default, but a feature flag to enable this sounds good to me!
