### ISSUE TITLE
Ability to make a HEAD request

### ISSUE THREAD

**Issue by andrewdavidmackenzie** [alexcrichton/curl-rust#380]
I was interested in using curl-rust to do a HEAD request instead of GET, just to check that a resource exists but avoid retrieving the body. 

I don't think that's possible now?

Would it be something interesting to add?

**Comment by sagebind** [comment]
As per the libcurl documentation, the option you are looking for is called [`CURLOPT_NOBODY`](https://curl.se/libcurl/c/CURLOPT_NOBODY.html), which corresponds to [`Easy::nobody`](https://docs.rs/curl/0.4.34/curl/easy/struct.Easy.html#method.nobody) and [`Easy2::nobody`](https://docs.rs/curl/0.4.34/curl/easy/struct.Easy2.html#method.nobody).

**Comment by andrewdavidmackenzie** [comment]
Thanks very much - I wasn't familiar with that.
