### ISSUE TITLE
Enabling aws-sigv4 integration

### ISSUE THREAD

**Issue by theawless** [alexcrichton/curl-rust#392]
Hi, I wanted to enable the [aws-sigv4 integration](https://curl.se/libcurl/c/CURLOPT_AWS_SIGV4.html) that was introduced with [curl version 7.75](https://github.com/curl/curl/pull/5703). Multiple cloud providers use this scheme, but many don't have adequate rust clients (SDKs or signing libraries). I think it would be pretty nifty to have this feature supported out of the box in curl-rust (and hopefully in [isahc](https://github.com/sagebind/isahc)). Q1. What are your thoughts on this?

Here's my work so far: https://github.com/alexcrichton/curl-rust/compare/master...theawless:aws-sigv4
* added the `aws-sigv4` method in the `Easy`, `Easy2`, and `Auth` structs
* added aws-sigv4 related options in curl-sys lib
* removed `CURL_DISABLE_CRYPTO_AUTH` from curl-sys build
* added crypto-related files (digest, sha256, hmac, etc) to curl-sys build

I noticed that removing `CURL_DISABLE_CRYPTO_AUTH` automatically starts building NTLM which I didn't intend to. The already existing flag `CURL_DISABLE_NTLM` didn't seem to work. I noticed that curl got rid of that flag [here in this commit](https://github.com/curl/curl/pull/6809). I haven't worked with curl before but I think it might be impacting other dependencies as well (at least the [code search](https://github.com/search?q=CURL_DISABLE_NTLM&type=code) shows many instances). Q2: Do you think that this could be reverted and should I start a discussion at their end?

**Comment by alexcrichton** [comment]
Seems reasonable to me to add this! If this requires fiddly bits as part of the build that's ok, the current build script is pretty specialized to what this crate needs as-is and if it needs more it's expected that we'd need to pull in more files and update things. I don't know ahead of time what changes are necessary to support this, but figuring it out on a PR seems fine by me.

**Comment by theawless** [comment]
@alexcrichton Just one last question before I close this issue and continue the work on a pull request.

Since [the commit](https://github.com/curl/curl/pull/6809) `CURL_DISABLE_NTLM` is not working.
Do you happen to know a for sure way to disable NTLM while building curl?

**Comment by alexcrichton** [comment]
Nah unfortunately I do not know.
