### ISSUE TITLE
Openssl as a submodule of curl-sys

### ISSUE THREAD

**Issue by mzr** [alexcrichton/curl-rust#397]
I see that there are features like `static-ssl` and `static-curl`. Curl is a submodule of sys-curl crate, however openssl isn't.
Why is that? Can it be added?

**Comment by sagebind** [comment]
OpenSSL is provided by the [`openssl-sys`](https://crates.io/crates/openssl-sys) crate, which is a dependency of `curl-sys`. We don't manage it ourselves, we let that crate do it for us.

**Comment by mzr** [comment]
Ok, got it. I thought that in order for the `static-ssl` feature to be effective, the crate has to be a submodule. I was badly wrong :)
