### ISSUE TITLE
Expose CURLOPT_HTTP09_ALLOWED

### ISSUE THREAD

**Issue by jbangelo** [alexcrichton/curl-rust#436]
The [`CURLOPT_HTTP09_ALLOWED` option](https://curl.se/libcurl/c/CURLOPT_HTTP09_ALLOWED.html) tells curl to accept HTTP/0.9 responses, which can be a response just a body and no headers. This option has been disabled by default starting in v7.66 of curl, though some use cases still require it to be enabled.

**Comment by sagebind** [comment]
This is now published in the [0.4.44 release](https://github.com/alexcrichton/curl-rust/releases/tag/0.4.44).
