### ISSUE TITLE
Release updated curl-sys (7.85.0) to crates.io

### ISSUE THREAD

**Issue by klensy** [alexcrichton/curl-rust#465]
Can recently updated #459 version be released to crates.io? Thanks.

It's marked as yanked (https://crates.io/crates/curl-sys/0.4.57+curl-7.85.0), but its simply unreleased?

**Comment by ehuss** [comment]
It was yanked because it is not working on Windows 11. See https://github.com/curl/curl/issues/9451 for more information.

**Comment by klensy** [comment]
Sadly, there no yank reason on crates.io displayed.

**Comment by sagebind** [comment]
See also #460 for context.

**Comment by klensy** [comment]
7.86 released with with fix, it seems.
