### ISSUE TITLE
Stop curl at specific point

### ISSUE THREAD

**Issue by Omicronlawful** [alexcrichton/curl-rust#510]
Im interested if its possible to stop the curl when parts of it where fetched
```
let v:Arc<Mutex<String>> = Arc::new(Mutex::new(String::new()));
    let temp = v.clone();
    easy.write_function(move |data| {
        temp.lock().unwrap().push_str(std::str::from_utf8(data).unwrap());
        if temp.lock().unwrap().contains("var ...") {
            //TODO: stop the request
        }
        Ok(data.len())
    }).unwrap();
    easy.perform().unwrap();
    ```

**Comment by sagebind** [comment]
No, libcurl is not designed to be interrupted during a transfer when using the [easy API](https://everything.curl.dev/libcurl/drive/easy); however, you can halt a transfer at any time when using the [multi API](https://everything.curl.dev/libcurl/drive/multi). I recommend looking up some guides on using the curl multi API. The entrypoint to the multi API in the Rust bindings is the aptly-named [`Multi`](https://docs.rs/curl/latest/curl/multi/struct.Multi.html) type.

Hope that helps!
