### ISSUE TITLE
Best Approach using Easy2 when uploading large files (Gigabytes)

### ISSUE THREAD

**Issue by LorenzoLeonardo** [alexcrichton/curl-rust#516]
Hello what will be the best approach in using Easy2 especially uploading huge files?
https://docs.rs/curl/latest/curl/easy/struct.Easy2.html#method.post_fields_copy

**Comment by sagebind** [comment]
The best way would usually be to implement [`read`](https://docs.rs/curl/latest/curl/easy/trait.Handler.html#method.read) or to provide a [`read_function`](https://docs.rs/curl/latest/curl/easy/struct.Easy.html#method.read_function), both of which correspond to [`CURLOPT_READFUNCTION`](https://curl.se/libcurl/c/CURLOPT_READFUNCTION.html). This allows you to stream bytes from a large data source in a streaming fashion.

**Comment by LorenzoLeonardo** [comment]
How to send the chunk of data via post_copy_fields?
