### ISSUE TITLE
curl smashes moka cache

### ISSUE THREAD

**Issue by jchimene** [alexcrichton/curl-rust#520]
However it (Easy transport) works with mini-moka. I think it has something to do with the curl process() method freeing memory. 
Debugging this is above my pay grade.
If this issue attracts any interest, I will work up a reproducer.
I've filed an issue w/ moka as well.

**Comment by jchimene** [comment]
It's looking like this is a lazy_static issue. Since it's being deprecated, I've switched the cache to once_cell. Seems to be working. I'm reserving the right to re-open this once I've cleaned up the carnage.

**Comment by jchimene** [comment]
It's the moka implementation of expire_after() that conflicts with curl. Somehow.

**Comment by tatsuya6502** [comment]
>  I've filed an issue w/ moka as well.

https://github.com/moka-rs/moka/issues/299

**Comment by sagebind** [comment]
I'm not really sure I understand what moka is or how it relates to curl, but from the linked issue it seems like the problem has been solved anyway. If I am mistaken then feel free to this issue. Thanks!
