### ISSUE TITLE
0.4.45: Compilation issue 

### ISSUE THREAD

**Issue by sarroutbi** [alexcrichton/curl-rust#548]
Hello. If I update to 0.4.45 version, I am seeing this error in compilation:
```bash
error[E0425]: cannot find value `CURLMOPT_MAX_CONCURRENT_STREAMS` in crate `curl_sys`
   --> /github/home/.cargo/registry/src/index.crates.io-6f17d22bba15001f/curl-0.4.45/src/multi.rs:380:36
    |
380 |         self.setopt_long(curl_sys::CURLMOPT_MAX_CONCURRENT_STREAMS, val as c_long)
    |                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in `curl_sys`
 ```
 Is it something particular to my project?
 
 Have dependencies changed with latest version?

**Comment by ehuss** [comment]
It sounds like your project maybe updated the `curl` crate without updating `curl-sys`. You should be able to fix it with `cargo update -p curl-sys`.

I posted #549 so that is enforced.

**Comment by sarroutbi** [comment]
Hello @ehuss .  I was able to resolve it by upgrading `curl-sys`, as you mentioned. Thanks for your quick response.
