### ISSUE TITLE
several years since last release, status of this project ?

### ISSUE THREAD

**Issue by JimFuller-RedHat** [alexcrichton/curl-rust#567]
There seems to be a lot of pending PRs ... issues ... just wondering if there are any plans for more active development that someone (like me) could contribute to - alternately thinking of a new set of curl bindings. thx in advance

**Comment by ehuss** [comment]
There are regular releases, almost with every curl release. If you are looking at the [releases page](https://github.com/alexcrichton/curl-rust/releases), yea we haven't been updating that. It's a bit of a chore to do things like that. Releases can be seen on the corresponding crates.io pages.

If you have a specific binding that you need for your project, feel free to open a PR to add it.

**Comment by JimFuller-RedHat** [comment]
ah my mistake .... thx for correcting me.

have you considered closing very old PR (seeing something from 2017) and what is status of open PR ... are they active ?

**Comment by alexcrichton** [comment]
Maintenance has albeit slowed for sure, but this is still an important dependency of Cargo itself so updates are made and bugs are fixed. New features are not necessarily actively being developed but PRs can be reviewed.
