### ISSUE TITLE
error: unsupported output in build script of `curl-sys v0.4.76+curl-8.10.1`: `cargo::rustc-check-cfg=cfg(libcurl_vendored,link_libnghttp2,link_libz,link_openssl,)`

### ISSUE THREAD

**Issue by glandium** [alexcrichton/curl-rust#576]
#575 accidentally increased the (undocumented) MSRV to 1.80, and older rust versions fail to compile.

**Comment by iamalwaysuncomfortable** [comment]
I'm Also experiencing this issue

**Comment by nabijaczleweli** [comment]
Just got this report downstream: https://github.com/nabijaczleweli/cargo-update/issues/277

This user is on the current Ubuntu LTS, which ships 1.75.
Naturally, I would like to avoid fielding more reports like this.

There's no reason to not spell this as `cargo:rustc-check-cfg` (just as there was no reason to devise the `cargo::` syntax in the first place, especially without a failover period).

**Comment by alexcrichton** [comment]
> Naturally, I would like to avoid fielding more reports like this.

Personally I find this tone abrasive and unnecessarily conflict-oriented. No one's trying to foist work onto you and force you to deal with things. Bugs like this happen, and it's a part of how OSS works. I'd encourage you to pause before making comments like this since it ends up not really helping anyone for you to vent frustration to strangers on the internet.

**Comment by nabijaczleweli** [comment]
Sorry, that's not what I meant by this. This was an ill-thought short-hand for "I expect to see more of these [from Ubuntu LTS users], so I hope to fix this myself in short order, and would like to hope for this to be releasable on its own.". my b for writing it so short

**Comment by alexcrichton** [comment]
Thanks for clarifying! Also a good reminder for me to assume good faith on everyone's benefit. This is a case of only-text communication not being easy, and I know I mess it up all the time as well. Regardless thanks for helping to fix!
