### ISSUE TITLE
Can't build on Windows

### ISSUE THREAD

**Issue by engstad** [alexcrichton/curl-rust#58]
```text
   Compiling curl-sys v0.1.5
Build failed, waiting for other jobs to finish...
failed to run custom build command for `curl-sys v0.1.5`
Process didn't exit successfully: `C:\GitHub\mtg-rust\target\build\curl-sys-c3e3bf354b130c95\build-script-build.exe` (status=101)
--- stderr
thread '<main>' panicked at 'called `Option::unwrap()` on a `None` value', C:\bot\slave\nightly-dist-rustc-win-64\build\src\libcore\option.rs:361


Compilation exited abnormally with code 101 at Mon Jan 26 15:17:55
```

**Comment by marcusball** [comment]
I'm getting the same error on v0.1.25

    failed to run custom build command for `curl-sys v0.1.25`
    Process didn't exit successfully: `[Path-to-project]\target\debug\build\curl-sys-b582fd2220a1331e\build-scrip
    t-build` (exit code: 101)
    --- stdout
    cargo:rustc-link-search=[Path-to-project]\target\debug\build\curl-sys-b582fd2220a1331e\out/lib
    cargo:rustc-link-lib=static=curl
    cargo:root=[Path-to-project]\target\debug\build\curl-sys-b582fd2220a1331e\out
    cargo:include=[Path-to-project]\target\debug\build\curl-sys-b582fd2220a1331e\out/include
    cargo:rustc-flags=-l ws2_32

    --- stderr
    thread '<main>' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore\option.rs:363

**Comment by alexcrichton** [comment]
Hm, could you try running with `RUST_BACKTRACE=1` and gist the error? This crate should in theory build just fine on Windows (as Cargo depends on it and uses it quite a bit), but there's often weird build environment things on Windows to deal with!

**Comment by marcusball** [comment]
After trying to investigate an unrelated issue, I realized I'm a derp and needed to actually have curl installed. I'm dumb sometimes. :disappointed_relieved:

**Comment by alexcrichton** [comment]
Hm in theory this shouldn't require you to have curl installed locally, it should be sufficient to just have a C compiler (as this will build from source if it can't find it installed).

**Comment by alexcrichton** [comment]
I think this is the same as https://github.com/alexcrichton/curl-rust/issues/71, so I'm going to close in favor of that.
