### ISSUE TITLE
Support SSL related configuration

### ISSUE THREAD

**Issue by carllerche** [alexcrichton/curl-rust#6]
Allow configuring CURL's SSL related settings.

**Comment by posix4e** [comment]
I'm curious what we are looking for here. What ssl capability are we looking for.

**Comment by insectatorious** [comment]
[Doc for ref](http://curl.haxx.se/libcurl/c/CURLOPT_SSL_VERIFYPEER.html).

I would be using this to make requests against a test environment where we have an in-house SSL certificate. In this case disabling the verification is not necessarily a bad thing (at least this is the easiest approach but may not be the most correct way).

Anyway, seeing as CURL supports this I thought this should as well.

**Comment by posix4e** [comment]
It's easier for me the more fine gained issues are. If it's just that one
thing let's change the title.
