### ISSUE TITLE
Make `curl::ffi::err::ErrCode` public in order to allow downstream usage of the try! macro

### ISSUE THREAD

**Issue by storedbox** [alexcrichton/curl-rust#61]
Need to be able to implement the `std::error::FromError<curl::ffi::err::ErrCode>` trait for custom types in order to use the try! macro

**Comment by illegalprime** [comment]
I would love this too, I'm working on a Firebase library that uses curl I need something to call the Errors that curl gets.

**Comment by ids1024** [comment]
:+1:
